ASSIGNMENT-9

Data Transformation

In [58]:
import numpy as np
import pandas as pd

In [59]:
df = pd.read_csv("/content/adult_with_headers (1).csv")

In [60]:
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [61]:

df.shape

(32561, 15)

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [63]:
df.describe()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [64]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [65]:
df.duplicated().sum()

np.int64(24)

In [66]:
df.drop_duplicates(inplace=True)

In [67]:
df.duplicated().sum()

np.int64(0)

In [68]:
df.dtypes

age                int64
workclass         object
fnlwgt             int64
education         object
education_num      int64
marital_status    object
occupation        object
relationship      object
race              object
sex               object
capital_gain       int64
capital_loss       int64
hours_per_week     int64
native_country    object
income            object
dtype: object

In [69]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_gain', 'capital_loss', 'hours_per_week', 'native_country',
       'income'],
      dtype='object')

In [70]:
df.clean=df.copy()

/tmp/ipykernel_2880/3337392917.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.clean=df.copy()

In [71]:
from sklearn.preprocessing import StandardScaler
Scaler = StandardScaler()
num_cols = [
    'age',
    'fnlwgt',
    'education_num',
    'capital_gain',
    'capital_loss',
    'hours_per_week'
]
df[num_cols]=Scaler.fit_transform(df[num_cols])

In [72]:
from sklearn.preprocessing import MinMaxScaler
Scaler = MinMaxScaler()
num_cols = [
    'age',
    'fnlwgt',
    'education_num',
    'capital_gain',
    'capital_loss',
    'hours_per_week'
]
df[num_cols]=Scaler.fit_transform(df[num_cols])

Standard Scaling is preferred when data is approximately normally distributed.

It transforms data to mean = 0 and standard deviation = 1.

Min-Max Scaling is preferred when values need to be in a fixed range, usually 0 to 1.

Min-Max Scaling is useful when a bounded range is important for the algorithm.

Both techniques make numerical features comparable in scale.

**Encoding Techniques:**

In [73]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
cat_cols = df.select_dtypes(include='object').columns

df[cat_cols].nunique()

workclass          9
education         16
marital_status     7
occupation        15
relationship       6
race               5
sex                2
native_country    42
income             2
dtype: int64

In [74]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['workclass'] = encoder.fit_transform(df['workclass'])

In [75]:
df['workclass'].unique()

array([7, 6, 4, 1, 2, 0, 5, 8, 3])

In [76]:
df['race']=encoder.fit_transform(df['race'])
df['race'].unique()
df['native_country']=encoder.fit_transform(df['native_country'])
df['native_country'].unique()
df['capital_gain_log'] = np.log1p(df['capital_gain'])

One-Hot Encoding avoids creating an artificial order between categories.

Its disadvantage is that it can create many columns when there are many categories.

Label Encoding is simple and keeps the data in a single column.

Its disadvantage is that the assigned numbers may create a false order between categories.

The choice depends on the number and nature of the categorical values

Feature Engineering:

In [82]:
df['capital_net'] = df['capital_gain'] - df['capital_loss']

In [83]:
df['capital_gain_log'] = np.log1p(df['capital_gain'])

In [84]:
df[['capital_gain', 'capital_loss', 'capital_net', 'capital_gain_log']].head()

   capital_gain  capital_loss  capital_net  capital_gain_log
0      0.021507           0.0     0.021507          0.021279
1      0.000000           0.0     0.000000          0.000000
2      0.000000           0.0     0.000000          0.000000
3      0.000000           0.0     0.000000          0.000000
4      0.000000           0.0     0.000000          0.000000